_target_: human_detection.pipeline.TrackingPipeline

config:
  _target_: human_detection.pipeline.TrackingPipelineConfig

  display_enabled: true
  display_window_name: Target Tracking

  video_enabled: true
  video_path: ${results.directory}/tracking.mp4

  render_bbox: true
  render_pose: true
  render_position: true
