type: camera

# Timestamp used as the base name of the result directory
name: ${now:%Y-%m-%d-%H-%M-%S}-camera

# Camera input source
source:
  _target_: human_detection.frame_source.PrimeSenseCameraSource
  openni2_redist_path: 'C:\Program Files\OpenNI2\Redist'
  width: 320
  height: 240
  fps: 30

