defaults:
  - source: video
  - person_detector: accurate
  - feature_extractor: osnet
  - target_matching: default
  - target_classifier: ridge
  - person_tracker: accurate
  - target_tracker: default
  - registration_pipeline: default
  - tracking_pipeline: default
  - _self_

device: cuda:0

paths:
  root: ${hydra:runtime.cwd}
  models_dir: ${paths.root}/models
  inputs_dir: ${paths.root}/inputs

target:
  # Name of the person to track
  name: ???

  # Directory containing reference images
  directory: ${paths.inputs_dir}/target/${.name}

results:
  # Directory for the current tracking task
  directory: ${paths.root}/results/${now:%Y-%m-%d-%H-%M-%S}-${source.name}-${target.name}

  crops:
    path: ${results.directory}/crops

  bbox:
    enabled: true
    path: ${results.directory}/bbox.pt

  tracking_video:
    enabled: true
    path: ${results.directory}/tracking.mp4

  debug_video:
    enabled: true
    path: ${results.directory}/debug.mp4

  display:
    enabled: true
    window_name: Target Tracking
